name: Deploy on Merge
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy API and Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - name: Build front end
        run: |
          npm ci
          npm run build
        working-directory: ./website
      - name: Copy build folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./website/build
          remote: /home/ubuntu/CalisthenicsGod/website/build
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          privateKey: ${{ secrets.SERVER_KEY }}
          port: 22
          rmRemote: true
      - name: Deploy Remotely
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/CalisthenicsGod
            git pull
            sudo docker-compose --env-file ./config/.env.production build caddy website backend
            sudo docker-compose down
            sudo docker system prune -f
            sudo docker-compose --env-file ./config/.env.production up -d caddy

# TODO build all locally then only transfer over required build files
