name: Deploy on Merge
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy API and Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /CalisthenicsGod
          git pull
          sudo docker-compose down
          ./startUp.sh production
        host: ${{ secrets.HOST }}
        user: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.SERVER_KEY}}
<<<<<<< HEAD
        port: 22
=======
>>>>>>> auto deploy script
