name: Deploy on Merge
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy API and Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SERVER_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/CalisthenicsGod
            git pull
            sudo docker-compose down
            ./startUp.sh production
