name: Deploy on Merge
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy API and Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
<<<<<<< HEAD
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /CalisthenicsGod
          git pull
          sudo docker-compose down
          ./startUp.sh production
        host: ${{ secrets.HOST }}
        user: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.SERVER_KEY}}
<<<<<<< HEAD
<<<<<<< HEAD
        port: 22
=======
>>>>>>> auto deploy script
=======
        port: 22
>>>>>>> port
=======
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SERVER_KEY}}
          port: 22
          script: |
            cd /CalisthenicsGod
            git pull
            sudo docker-compose down
            ./startUp.sh production
>>>>>>> now
