name: Build, Test API on Push
on: push
jobs:
  buildAPI:
    name: Build API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sudo docker-compose build backend
    - name: deploy
      run: sudo docker-compose up -d backend
  buildWebsite:
    name: Build Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sudo docker-compose build website
    - name: deploy
      run: sudo docker-compose up -d website
  testAPI:
    name: Test API
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: deploy for test
      run: sudo docker-compose up -d backend
    - name: test
      run: |
        cd backend/
        npm install
        npm run test