name: Build, Test API on Push
on: push
jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sudo docker-compose build
    - name: deploy
      run: sudo docker-compose up -d
  test:
    name: Test API
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: deploy for test
      run: sudo docker-compose up -d
    - name: test
      run: |
        cd backend/
        npm install
        npm run test