name: Build, Test API on Push
on: push
jobs:
  build:
    needs: setup
    name: Build and Run API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: backend build
      run: sudo docker-compose build
    - name: backend up
      run: |
        sudo docker-compose up
  test:
    name: Test API
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v1
    - name: test backend
      run: npm run test