name: Build, Test API on Push
on: push
jobs:
  build:
    name: Build, Run and Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - name: backend build
      run: sudo docker-compose build
    - name: backend up
      run: sudo docker-compose up -d
    - name: install npm dependencies
      run: npm install
    - name: test backend
      run: npm run test